### ISSUE TITLE
Add label x:size/small to all dependency update PRs

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/org-wide-files#92]

**Comment by ErikSchierboom** [comment]
I like this idea. The main thing to figure out is what the `dependabot.yml` file should look like, as it will apply to all tracks.

Here's the [javascript configuration](https://github.com/exercism/javascript/blob/main/.github/dependabot.yml):

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
```

And here're the [csharp configuration](https://github.com/exercism/csharp/blob/main/.github/dependabot.yml):

```yaml   
version: 2

updates:
  # Keep GitHub Actions dependencies up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Keep NuGet dependencies up-to-date
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
```

The `github-actions` part could be universally applied to all track and tooling repos I think, as it is good practice to keep those up-to-date. For the rest we could possibly just use appends, but that would mean that more general configuration settings could _not_ be overridden in tracks I think. I have no idea how problematic that is though.

**Comment by SaschaMann** [comment]
It would be possible to extend the append system so that it can be a config file that overwrites or appends individual settings, if that's necessary.

**Comment by ErikSchierboom** [comment]
For reference, here are all the `dependabot.yml` files:

<details><summary>05ab1e</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>ada</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>arm64-assembly</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>babashka</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>ballerina</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>bash</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>c-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>c</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>ceylon</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>cfml</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>clojure</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>clojurescript-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>clojurescript</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>coffeescript-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>coffeescript</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>common-lisp</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>configlet</summary>
<p>

```yaml
version: 2

updates:
  # Enable updates to the dependencies of our workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
```

</p>
</details>
<details><summary>coq</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>cpp-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>cpp</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>crystal-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>crystal</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>csharp</summary>
<p>

```yaml
version: 2

updates:
  # Keep GitHub Actions dependencies up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Keep NuGet dependencies up-to-date
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>d-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>d</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>dart-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>dart</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>delphi</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>dotnet-tests</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>elixir</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>elm</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>emacs-lisp-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>emacs-lisp</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>erlang</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>factor</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>forth</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>fortran-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>fortran</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>fsharp</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>generic-analyzer</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>generic-representer</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>generic-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>gleam</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>gnu-apl</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>go</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>groovy</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>haskell-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>haskell</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>haxe</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>idris</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>io</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>j</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>java</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>javascript</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>julia</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>kotlin</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>lfe-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>lfe</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>lua</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>mips-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>mips</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>nim-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Enable updates to the dependencies of our workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly

  # Enable updates to the dependencies of our Dockerfile
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
      time: '05:00'
```

</p>
</details>
<details><summary>nim</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>nix</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>objective-c-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>objective-c</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>ocaml</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>org-wide-files</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>perl5-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>perl5</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>pharo-smalltalk</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>php</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>plsql</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>pony</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>powershell</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>prolog</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>purescript</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>python</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>r-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>r</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>racket-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>racket</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>raku-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>raku</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>reasonml</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>red-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>red</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>ruby</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>rust</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>scala</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>scheme</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>shen</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>sml</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>solidity</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>swift</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>system-verilog</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>tcl</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>typescript</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  # Enable version updates for npm (yarn)
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'

  # Enable version updates for npm (yarn)
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the common directory
    directory: '/common/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>vbnet-test-runner</summary>
<p>

```yaml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

</p>
</details>
<details><summary>vbnet</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>vimscript</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>x86-64-assembly</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
<details><summary>zig</summary>
<p>

```yaml
version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

</p>
</details>
